#server:
#  port: 5002
#  servlet:
#    context-path: /tms
#
#spring:
#  application:
#    name: tour-test
#  cloud:
#    nacos:
#      config:
#        server-addr: ${nacosServer}
#        namespace: ${namespaceId}
#        username: nacos
#        password: nacos
#        file-extension: yaml
#        enabled: true
#        refresh-enabled: true
#        import-check:
#          enabled: false
#        shared-configs:
#          - data-id: tem-test.yaml
#            group: DEFAULT_GROUP
#            refresh: true
#
#dubbo:
#  registry:
#    address: nacos://${nacosServer}?namespace=${namespaceId}
#    username: nacos
#    password: nacos
#  protocol:
#    name: dubbo
#    port: -1
#  application:
#    name: ${spring.application.name}
#
#---
#################################--------------dev-------------##################################################
#spring:
#  config:
#    activate:
#      on-profile: dev
#namespaceId: dev
#nacosServer: 192.168.31.37:8848
#---
#################################--------------test-------------##################################################
#spring:
#  config:
#    activate:
#      on-profile: test
#namespaceId: test
#nacosServer: 127.0.0.10:8848